feat: message silver and core table
MetricsDAO/terra_dbt pull request #22
Opened 2022-10-09 04:58 UTC by geewynn

# Description
Message core__fact and silver__message table

# Tests

- [x] Please provide evidence of your successful `dbt run` / `dbt test` here
- [x] Any comparison between `prod` and `dev` for any schema change
![image](https://user-images.githubusercontent.com/29405050/194738766-bc16d2be-e006-4b52-b030-033b3f4c52c9.png)
![image](https://user-images.githubusercontent.com/29405050/194738778-82f881b3-90c4-42b0-bd6d-13fb0c8775a6.png)

# Checklist
- [x] Follow [dbt style guide](https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md)
- [x] Tag the person(s) responsible for reviewing proposed changes
- [x] Notes to deployment, if a `full-refresh` is needed for any table
- [x] Run `git merge main` to pull any changes from remote into your branch prior to merge.

2022-10-09 06:18 UTC, eevui requested changes
Got a couple comments.

For all sql: no caps on keywords.

2022-10-09 06:18 UTC, eevui commented on models/silver/silver__messages.sql
> +    ORDER BY
I think we should leave ordering out for the analyst by default.

2022-10-09 06:18 UTC, eevui commented on models/silver/silver__messages.sql
> +WITH txs AS (
Follow dbt guidelines: no caps for sql keywords.

2022-10-09 06:18 UTC, eevui commented on models/silver/silver__messages.sql
> +                    REGEXP_REPLACE(
I take this regexp selects the digit portion? Consider `regexp_substr` to select a substring

2022-10-09 06:18 UTC, eevui commented on models/silver/silver__messages.sql
> +    ORDER BY
Is ordering here important?

2022-10-09 06:18 UTC, eevui commented on models/silver/silver__messages.yml
> +        description: "{{ doc('_ingested_at') }}"
Lacking tests.

2022-10-09 06:18 UTC, eevui commented on models/core/core__fact_messages.sql
> +
Please follow style guide: no caps on keywords.

Also, perhaps use a `final` CTE.

2022-10-09 06:18 UTC, eevui commented on models/silver/silver__messages.sql
> +    FROM
Missing incremental filter.

2022-10-09 06:18 UTC, eevui commented on models/silver/silver__messages.sql
> +        {{ ref('silver__blocks') }}
Missing incremental filter _or_ cut down on this `blocks` CTE ASAP. Take only rows that you need.

2022-10-09 06:18 UTC, eevui commented on models/silver/silver__messages.sql
> +        DISTINCT CONCAT(
Don't think we need a `distinct` here any more?

2022-10-09 06:18 UTC, eevui commented on models/core/core__fact_messages.yml
> +      - name: message_id
Add `unique` test to primary keys.

2022-10-09 15:11 UTC, D0R11 commented on models/silver/silver__messages.sql
> +    FROM
agree

2022-10-09 15:12 UTC, D0R11 commented on models/silver/silver__messages.sql
> +        {{ ref('silver__blocks') }}
chain id is needed according to what was agreed upon in discord but it's only in the `blocks` table so I had to fetch it there

2022-10-09 15:15 UTC, D0R11 commented on models/silver/silver__messages.sql
> +        DISTINCT CONCAT(
Running it without distinct here would make an error duplicate key. You can try the query [here](https://app.snowflake.com/us-east-1/dqa62717/w4X7vAXtGbri#query).

2022-10-09 15:15 UTC, D0R11 commented on models/core/core__fact_messages.yml
> +      - name: message_id
agree

2022-10-09 15:17 UTC, D0R11 commented on models/silver/silver__messages.sql
> +WITH txs AS (
`::DATE` is not included in the column name too, and the unique id is the newly-created `message_id` instead

2022-10-09 15:19 UTC, D0R11 commented on models/silver/silver__messages.sql
> +    ORDER BY
Ah, no. Should have removed that, apologies

2022-10-09 15:23 UTC, D0R11 commented on models/silver/silver__messages.sql
> +                    REGEXP_REPLACE(
yup, was originally trying to do something else so I tried web3_analyst's suggestion but you're right. The code could have been shorter, sorry

2022-10-10 13:29 UTC, eevui commented on models/silver/silver__messages.sql
> +        {{ ref('silver__blocks') }}
Ah yeah, either join with transactions or perform incremental filter. Blocks and its txs are ingested at the same time, afaik.

2022-10-10 14:57 UTC, D0R11 commented on models/silver/silver__messages.sql
> +        {{ ref('silver__blocks') }}
I added an incremental filter on the latest commit can you check?

2022-10-10 14:57 UTC, D0R11 commented on models/core/core__fact_messages.yml
> +      - name: message_id
done

2022-10-10 15:04 UTC, D0R11 commented on models/core/core__fact_messages.sql
> +
I think this is okay

2022-10-11 02:01 UTC, eevui approved these changes
LGTM!

2022-10-11 02:04 UTC, merged