fix decimal place on swap table
MetricsDAO/terra_dbt pull request #56
Opened 2022-11-23 13:58 UTC by robel91

![fix_decimal_test](https://user-images.githubusercontent.com/92173230/203565030-1d1dac6c-8304-4c1c-95c4-e0e962af40f0.png)
![fix_decimal_run](https://user-images.githubusercontent.com/92173230/203565035-02682d42-7863-4fe7-b12a-723fbb647774.png)
# Description

_Please include a summary of changes and related issue (if any)._

# Tests

- [ ] Please provide evidence of your successful `dbt run` / `dbt test` here
- [ ] Any comparison between `prod` and `dev` for any schema change

# Checklist
- [ ] Follow [dbt style guide](https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md)
- [ ] Run `git merge main` to pull any changes from remote into your branch prior to merge.
- [ ] Tag the person(s) responsible for reviewing proposed changes
- [ ] **IMPORTANT** Note for deployment if a `full-refresh` is needed for any model this PR impacts.
     - If any schema is changing, whether it be a table or a view, we will need to run a `full-refresh` in prod to avoid errors with the scheduled refresh jobs.
     - The PR can be reviewed, but should not be merged unless by someone with prod access.
         - Tag `forgxyz` if a full-refresh will be required on prod.

2022-11-28 15:29 UTC, geewynn commented on models/silver/silver__dex_swaps.sql
> -            round(from_amount / pow(10, 6)) as from_decimal,
Maybe use a fixed value for the decimals, 6 until we have the  token labels table.

2022-11-28 15:29 UTC, geewynn commented on models/silver/silver__dex_swaps.sql
> -            round(to_amount / pow(10, 6)) as to_decimal,
same here.

2022-11-28 16:16 UTC, forgxyz requested changes

2022-11-28 16:16 UTC, forgxyz commented on models/silver/silver__dex_swaps.sql
> -            round(from_amount / pow(10, 6)) as from_decimal,
Yes, the `x_decimal` column is supposed to be the number of decimals the analyst uses to adjust the raw amount to a decimal-adjusted amount. For example, on ethereum, if you look at the contract for [Dai on Etherscan](https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f) the **Profile Summary** lists 18 as the decimal. This is the decimal precision of the raw number we see on chain.

This column is not adjusted amount.

2022-11-28 18:17 UTC, liltims77 commented
@forgxyz  you mean round(from_amount / pow(10, adjusted_amount - raw_amount)) as from_decimal?

2022-11-28 18:23 UTC, forgxyz commented
No, I'll tag you in Discord for context

2022-11-30 16:08 UTC, geewynn approved these changes

2022-11-30 16:51 UTC, forgxyz approved these changes

2022-11-30 16:51 UTC, merged