Feat: Create new NFT Mints table
MetricsDAO/terra_dbt pull request #60
Opened 2022-11-28 17:51 UTC by D0R11

# Description

Creates the NFT Mints table. Solves issue #50.

# Tests

- [x] Please provide evidence of your successful `dbt run` / `dbt test` here

**dbt run**
```bash
root@c5d0db7e7d3c:/terra/models/silver# dbt run --select silver__nft_mints --full-refresh
17:19:02  Running with dbt=1.2.0
17:19:09  Found 67 models, 564 tests, 0 snapshots, 0 analyses, 684 macros, 2 operations, 0 seed files, 44 sources, 0 exposures, 0 metrics
17:19:09  
17:19:36  
17:19:36  Running 2 on-run-start hooks
17:19:36  1 of 2 START hook: terra.on-run-start.0 ........................................ [RUN]
17:19:36  1 of 2 OK hook: terra.on-run-start.0 ........................................... [OK in 0.00s]
17:19:36  2 of 2 START hook: terra.on-run-start.1 ........................................ [RUN]
17:19:52  2 of 2 OK hook: terra.on-run-start.1 ........................................... [SUCCESS 1 in 16.23s]
17:19:52  
17:19:53  Concurrency: 4 threads (target='dev')
17:19:53  
17:19:53  1 of 1 START incremental model silver.nft_mints ................................ [RUN]
17:19:59  1 of 1 OK created incremental model silver.nft_mints ........................... [SUCCESS 1 in 6.28s]
17:19:59  
17:19:59  Finished running 1 incremental model, 2 hooks in 0 hours 0 minutes and 49.72 seconds (49.72s).
17:19:59  
17:19:59  Completed successfully
17:19:59
17:19:59  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

**dbt test**
```bash
root@c5d0db7e7d3c:/terra/models/silver# dbt test --select silver__nft_mints
17:25:01  Running with dbt=1.2.0
17:25:08  Found 67 models, 567 tests, 0 snapshots, 0 analyses, 684 macros, 2 operations, 0 seed files, 44 sources, 0 exposures, 0 metrics
17:25:08  
17:25:37  
17:25:37  Running 2 on-run-start hooks
17:25:37  1 of 2 START hook: terra.on-run-start.0 ........................................ [RUN]
17:25:37  1 of 2 OK hook: terra.on-run-start.0 ........................................... [OK in 0.00s]
17:25:37  2 of 2 START hook: terra.on-run-start.1 ........................................ [RUN]
17:25:49  2 of 2 OK hook: terra.on-run-start.1 ........................................... [SUCCESS 1 in 12.35s]
17:25:49  
17:25:50  Concurrency: 4 threads (target='dev')
17:25:50  
17:25:50  1 of 22 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_BLOCKCHAIN__STRING__VARCHAR  [RUN]
17:25:50  2 of 22 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_BLOCK_ID__NUMBER__FLOAT  [RUN]
17:25:50  3 of 22 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_BLOCK_TIMESTAMP__TIMESTAMP_NTZ  [RUN]
17:25:50  4 of 22 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_CHAIN_ID__STRING__VARCHAR  [RUN]
17:25:56  4 of 22 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_CHAIN_ID__STRING__VARCHAR  [PASS in 6.09s]
17:25:56  5 of 22 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_CONTRACT_ADDRESS__STRING__VARCHAR  [RUN]
17:25:56  3 of 22 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_BLOCK_TIMESTAMP__TIMESTAMP_NTZ  [PASS in 6.37s]
17:25:56  6 of 22 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_CURRENCY__STRING__VARCHAR  [RUN]
17:25:57  1 of 22 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_BLOCKCHAIN__STRING__VARCHAR  [PASS in 6.61s]
17:25:57  7 of 22 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_DECIMAL__NUMBER  [RUN]
17:25:57  2 of 22 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_BLOCK_ID__NUMBER__FLOAT  [PASS in 7.01s]
17:25:57  8 of 22 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_MINTER__STRING__VARCHAR  [RUN]
17:26:01  5 of 22 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_CONTRACT_ADDRESS__STRING__VARCHAR  [PASS in 4.71s]
17:26:01  9 of 22 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_MINT_ID__STRING__VARCHAR  [RUN]
17:26:01  6 of 22 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_CURRENCY__STRING__VARCHAR  [PASS in 4.81s]
17:26:01  10 of 22 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_MINT_PRICE__NUMBER  [RUN]
17:26:01  7 of 22 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_DECIMAL__NUMBER  [PASS in 4.83s]
17:26:01  11 of 22 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_TOKEN_ID__NUMBER  [RUN]
17:26:02  8 of 22 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_MINTER__STRING__VARCHAR  [PASS in 4.90s]
17:26:02  12 of 22 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_TX_ID__STRING__VARCHAR  [RUN]
17:26:05  10 of 22 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_MINT_PRICE__NUMBER  [PASS in 4.13s]
17:26:05  13 of 22 START test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_TX_SUCCEEDED__BOOLEAN  [RUN]
17:26:06  11 of 22 WARN 1 dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_TOKEN_ID__NUMBER  [WARN 1 in 4.69s]
17:26:06  14 of 22 START test dbt_utils_unique_combination_of_columns_silver__nft_mints_MINT_ID  [RUN]
17:26:06  9 of 22 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_MINT_ID__STRING__VARCHAR  [PASS in 5.33s]
17:26:06  15 of 22 START test not_null_silver__nft_mints_BLOCKCHAIN ...................... [RUN]
17:26:07  12 of 22 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_TX_ID__STRING__VARCHAR  [PASS in 4.72s]
17:26:07  16 of 22 START test not_null_silver__nft_mints_BLOCK_ID ........................ [RUN]
17:26:10  13 of 22 PASS dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_TX_SUCCEEDED__BOOLEAN  [PASS in 4.89s]
17:26:10  17 of 22 START test not_null_silver__nft_mints_BLOCK_TIMESTAMP ................. [RUN]
17:26:11  15 of 22 PASS not_null_silver__nft_mints_BLOCKCHAIN ............................ [PASS in 4.35s]
17:26:11  18 of 22 START test not_null_silver__nft_mints_CHAIN_ID ........................ [RUN]
17:26:11  16 of 22 PASS not_null_silver__nft_mints_BLOCK_ID .............................. [PASS in 4.00s]
17:26:11  19 of 22 START test not_null_silver__nft_mints_MINT_ID ......................... [RUN]
17:26:11  14 of 22 PASS dbt_utils_unique_combination_of_columns_silver__nft_mints_MINT_ID  [PASS in 4.82s]
17:26:11  20 of 22 START test not_null_silver__nft_mints_TX_ID ........................... [RUN]
17:26:15  17 of 22 PASS not_null_silver__nft_mints_BLOCK_TIMESTAMP ....................... [PASS in 4.49s]
17:26:15  21 of 22 START test not_null_silver__nft_mints_TX_SUCCEEDED .................... [RUN]
17:26:15  18 of 22 PASS not_null_silver__nft_mints_CHAIN_ID .............................. [PASS in 4.40s]
17:26:15  22 of 22 START test unique_silver__nft_mints_MINT_ID ........................... [RUN]
17:26:15  19 of 22 PASS not_null_silver__nft_mints_MINT_ID ............................... [PASS in 4.69s]
17:26:16  20 of 22 PASS not_null_silver__nft_mints_TX_ID ................................. [PASS in 5.11s]
17:26:19  21 of 22 PASS not_null_silver__nft_mints_TX_SUCCEEDED .......................... [PASS in 3.89s]
17:26:19  22 of 22 PASS unique_silver__nft_mints_MINT_ID ................................. [PASS in 4.00s]
17:26:19  
17:26:19  Finished running 22 tests, 2 hooks in 0 hours 1 minutes and 10.67 seconds (70.67s).
17:26:19  
17:26:19  Completed with 1 warning:
17:26:19
17:26:19  Warning in test dbt_expectations_expect_column_values_to_be_in_type_list_silver__nft_mints_TOKEN_ID__NUMBER (models/silver/silver__nft_mints.yml)
17:26:19    Got 1 result, configured to  [...]

2022-11-29 10:39 UTC, geewynn requested changes

2022-11-29 10:39 UTC, geewynn commented on models/silver/silver__nft_mints.yml
> +                - NUMBER
There are some non number token id, maybe add a varchar column type to clear the warning.

image.png

2022-11-30 02:54 UTC, D0R11 commented on models/silver/silver__nft_mints.yml
> +                - NUMBER
Applied the changes you suggested

2022-11-30 10:16 UTC, geewynn approved these changes

2022-11-30 10:17 UTC, merged