add jinja to fix the break
MetricsDAO/terra_dbt pull request #70
Opened 2022-11-30 23:20 UTC by robel91

![all_test_passing](https://user-images.githubusercontent.com/92173230/204928655-f938433f-9668-483c-b60a-7f0f4ca36f3e.png)
```
PS C:\Users\Owner\git_flipside\terra_dbt> dbt run -m models\core\core__ez_swaps.sql               
23:12:55  Running with dbt=1.2.1
23:12:55  Found 67 models, 567 tests, 0 snapshots, 0 analyses, 693 macros, 2 operations, 0 seed files, 44 sources, 0 exposures, 0 metrics
23:12:55  
23:13:04  
23:13:04  Running 2 on-run-start hooks
23:13:04  1 of 2 START hook: terra.on-run-start.0 ........................................ [RUN]
23:13:04  1 of 2 OK hook: terra.on-run-start.0 ........................................... [OK in 0.00s]
23:13:04  2 of 2 START hook: terra.on-run-start.1 ........................................ [RUN]
23:13:13  2 of 2 OK hook: terra.on-run-start.1 ........................................... [SUCCESS 1 in 8.96s]
23:13:13
23:13:13  Concurrency: 4 threads (target='dev')
23:13:13  
23:13:13  1 of 1 START view model core.ez_swaps .......................................... [RUN]
23:13:15  1 of 1 OK created view model core.ez_swaps ..................................... [SUCCESS 1 in 1.82s]
23:13:15
23:13:15  Finished running 1 view model, 2 hooks in 0 hours 0 minutes and 19.88 seconds (19.88s).
23:13:15  
23:13:15  Completed successfully

```# Description

_Please include a summary of changes and related issue (if any)._

# Tests

- [ ] Please provide evidence of your successful `dbt run` / `dbt test` here
- [ ] Any comparison between `prod` and `dev` for any schema change

# Checklist
- [ ] Follow [dbt style guide](https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md)
- [ ] Run `git merge main` to pull any changes from remote into your branch prior to merge.
- [ ] Tag the person(s) responsible for reviewing proposed changes
- [ ] **IMPORTANT** Note for deployment if a `full-refresh` is needed for any model this PR impacts.
     - If any schema is changing, whether it be a table or a view, we will need to run a `full-refresh` in prod to avoid errors with the scheduled refresh jobs.
     - The PR can be reviewed, but should not be merged unless by someone with prod access.
         - Tag `forgxyz` if a full-refresh will be required on prod.

2022-12-01 20:55 UTC, forgxyz commented on models/silver/silver__dex_swaps.sql
> +            round(to_amount / pow(10, 6)) as to_decimal,
I believe this should just be 6, right?

2022-12-01 20:57 UTC, forgxyz commented on models/silver/silver__dex_swaps.sql
> +            concat(s.tx_id, '-', msg_index, '-', s.contract_address, '-') as swap_id,
A suggestion - you can use CONCAT_WS to specify a divider, something like CONCAT_WS('-', s.tx_id, msg_index, s.contract_address). Just a bit less to type out

2022-12-01 20:58 UTC, forgxyz commented on models/silver/silver__dex_swaps.sql
> +        left outer join {{ ref("silver__transactions") }} t on s.tx_id = t.tx_id
I would not use ref against something like the transactions table in a join. This should be in a CTE with the incremental load filter on as that should be more performant.

2022-12-01 20:59 UTC, forgxyz commented on models/silver/silver__dex_swaps.sql
> +            {{ ref("core__dim_address_labels") }} l on l.address = s.contract_address
This is a dimensional table, so would not be a large to scan as transactions. However, I would pull this reference function out into a CTE and join to the CTE instead of the ref as that is best practice.

2022-12-01 21:01 UTC, forgxyz requested changes
Runs and tests without error. I added some comments in-line for review

2022-12-01 21:03 UTC, forgxyz commented
Note for deployment - a full-refresh is required due to the changing unique key

2022-12-01 21:44 UTC, robel91 commented
Thanks @forgxyz . I will update them now

2022-12-02 16:58 UTC, forgxyz approved these changes

2022-12-02 18:23 UTC, merged